### ISSUE TITLE
Client Side Buffer Oddities

### ISSUE THREAD

**Issue by klassenjs** [geomoose/gm3#107]
Continuing the discussion here from PR #88 since it has been merged:

@elil  Using 8487451 on https://demo.geomoose.org/3.0/ I did select features, draw polygon, change buffer to 500 ft, go and it appears to show the original polygon, the buffer, and the selected parcels.  Is this working as you think it should?

![screenshot from 2017-05-31 10 30 52](https://cloud.githubusercontent.com/assets/165622/26640109/5faa3b2c-45ec-11e7-961d-5fc9fbfe79ae.png)

I see multi-point is only using the last point.  Select Features, Draw Multi-Point, set buffer 500ft, go:
![screenshot from 2017-05-31 10 35 52](https://cloud.githubusercontent.com/assets/165622/26640292/f1c86664-45ec-11e7-9e93-ddcfddce2f37.png)

I also see that the buffer setting stays set to what it was when re-entering the Select Features tool, but the form elements are set to 0ft.  Changing the buffer distance form element updates the buffer to the value displayed.
![screenshot from 2017-05-31 10 39 42](https://cloud.githubusercontent.com/assets/165622/26640495/7b121802-45ed-11e7-990c-5dc69c179919.png)

**Comment by elil** [comment]
Yes, showing original input geometry is working as I think it should.  

I note the same Draw Multi-Point issue as you with only bufferng the last point.  Also, Draw Multi-Point does not remove the previous drawing.  

![multipoint_doesnt_clear_previous_drawing](https://cloud.githubusercontent.com/assets/5263258/26642742/bb61360e-45e3-11e7-91cb-8b0ed6de2d77.png)

We also need to decide when to clear the previous selection see below:
![when_to_clear_previous_selection](https://cloud.githubusercontent.com/assets/5263258/26642820/1037b8ba-45e4-11e7-8970-90a67312f8a0.png)

**Comment by klassenjs** [comment]
#110 Fixes what I saw so I am going to merge that (under the strategy that it is at least better than it was).
@elil, can you verify if this fixes what you saw or if another PR is needed?

**Comment by theduckylittle** [comment]
I would <3 a summary list of what quirks are still happening.

**Comment by elil** [comment]
Summary:
- [X] show original geometry
- [X] Multi Point uses all points
- [X] Multi Point removes previous geometry
- [X] Re-entering the Select Features tool, form elements and buffer match
- [ ]  Clear previous selection once new drawing is completed (on multi point, would need to use Go button or first point instead of completion of geometry). (or otherwise determine proper time to clear previous selection.)

Additional:
- [ ] Select can partially disable Measure.  

1. Select features with a line or polygon (and presumably select from: Drawing and Markup)
2. Switch to measure and either line or polygon will be engaged.  
3. Clicking does not work, must change geometry selection type and then it works.

**Comment by theduckylittle** [comment]
1. Clear previous selection once new drawing is completed: Do you mean, we should clear the grid/highlight features once the user has finished a new drawing? It might be easier to do once they start just given the chain of events.

2. Select breaking measure.  Got it.

I think these are autonomous tickets though.  If the *buffering* is working, let's write up those two tickets and close this one.

**Comment by elil** [comment]
see #112 and #113
