### ISSUE TITLE
Projections - The Final Answer

### ISSUE THREAD

**Issue by theduckylittle** [geomoose/gm3#108]
@klassenjs Here is our dumping ground to discuss how feature projections once they hit the services.

EPSG:4326
Pros:
* Familiar coordinates at local and global levels. This is particularly useful for things like Zoom-to-point and bounding box definitions.
* "Easy" reprojection 
* Relatively simple to make consistent across the application.
* KML and GeoJSON spec 4326 as the bespoke projection.
Cons:
* Wasted energy if the service can or does return map coordinates.
* JavaScript struggles with super-high precision floats, so very-very-local level survey stuff could get "off"

"Native Map" Coordinates -- Currently 3857
Pros:
* The coordinates that are in the dataset are likely to be the ones seen in the map.
Cons:
* Native 4326 datasets will need to get "projected in" to the application (KML, GeoJSON)

I like the familiarity of using 4326 in places.  It means the underlying data projection could change and things like templates don't need to change.  So ostensibly you could configure a version of the application in "local" coordinates for more precise survey work and web-merc for general consumption (to use widely available imagery) without needing to change anything in the mapbook.

FWIW, neither decision effects measurements or buffers as that casts everything to a relevant UTM projection to ensure the measurements are valid.

**Comment by klassenjs** [comment]
I'm not sure what to think about this.  IIRC: Our past practice was to normalize everything to the map projection internally but also provide easy access to 4326 coordinates for services.

It doesn't much matter for points (as long as all projections involved are valid in the are of interest), but I know 4326 (and even 3857) have major issues with preserving shapes of lines and polygons, especially as you get closer to the poles and probably near the date line too (because the common projection libraries only re-project the vertexes and not the edges).  Thus, re-projecting a dataset can cause problems depending on the two projections, where on earth, and tolerance of the application to error, which implies to me that we need to give the administrator the ability to choose what best fits their use.

**Comment by theduckylittle** [comment]
This was "re" fixed in a more recent PR. The *answer* is that all internally stored features should be stored in Mapping coordinates.
