### ISSUE TITLE
Add all Geomoose source to debug.html

### ISSUE THREAD

**Issue by brentfraser** [geomoose/gm3#269]
To allow debugging of the Geomoose core Javascript.

**Comment by theduckylittle** [comment]
@brentfraser - It technically is. All the code is there but if you  really want to setup a dev environment, you'll need to look at the pertinent quickstarts.  Because we're using JSX and ES6 conventions the Javascript needs to get transpiled using webpack+babel before getting served to the client. 

See here for Windows: http://geomoose.github.io/gm3/install_on_windows.html
And here for Un*x: http://geomoose.github.io/gm3/quickstart.html

Cheers!
