### ISSUE TITLE
How should we organize demo/sample applications?

### ISSUE THREAD

**Issue by klassenjs** [geomoose/gm3#27]
Right now we have three ways of generating/packaging the demos:

1) geomoose/gm3:/demo
2) geomoose/gm3-demo-mobile
3) klassenjs/gm3-demos

None of them are great, but they all have their advantages too.  So, how do
combine the approaches to one best version?

1) + +Being in with the source, simple packaging and easy to test/maintain

   - -Not a good example for others (layout)
   - -Duality of being "just for dev/testing" but is likely the only demo 
     to be maintained.
   - -Easy to cheat and not notice (use stuff outside of dist, non public API)
   - -Easy to change at same time as lib means breaking changes in the lib
     are less likely to be noticed
   - -Only easily supports one demo (but that could be a very complete demo).

2) + +Uses npm for dependency management, but only for jquery
   + +Provides isolation between the lib and apps that depend on it
   + +Easy to understand layout - uses npm in a standard pattern
   + +Can easily be packaged as a zip and will just work
      (with node_modules pre-populated)

   - -Not at good example of how to install for real
     - -Duplication of config between mobile and desktop
     - -node_modules is (necessarily) web server accessible
   
3) + +Uses npm for dependency management
   + +Provides isolation between the lib and apps
   + +Most like what I would want to actually deploy
     + +Shared configuration (mapbook.xml, config.js)
     + +Shared libraries
     + +Desktop and Mobile both available
     + +Structure to add more "demo" apps
   + +Possible to build zip/tgz/ms4w.zip packages directly via grunt

   - -Most complex layout and build
     - -npm only puts stuff into node_modules so there are a lot of
       file copy operations to build a usable directory structure.
     - -This makes it more fidgety to substitute a git repo for a npm 
       resource.
   - -package.json has to include deps for all demos, but can't document
     which deps belong to which.

Thoughts:
  * We have a goal of easy updates.
  * We have declared geomoose/gm3 is a library
  * So everything in demo (or equiv) is now part of the user's app.

  * How do the user app (test.js/index.html) get updated? 
      Sure, The user does it.  But how do we communicate that?  How do we
      provide help for that on the list?

  * Semver then means minor and patch changes to gm3 cannot break user apps.

How many demos should there be?  How many can we realistically maintain? 
Possible ideas for additional demos:
  1) a non-mapbook driven demo
  2) a responsive demo
        can we put mobile and desktop in the same folder and have the JS
        pick (window.location) based on browser ("Fetch Desktop Version" 
        on mobile)
  3) Minimal UI embedded in another page

Services are a mess right now too:
  1) How does a user add a service?
      Shouldn't it be defined in their app and registered with the library 
      rather than essentially require a fork of GM3?
  2) Why aren't standard services compiled? 
      And thus need to be listed separately in index.html?

**Comment by theduckylittle** [comment]
Okay, I'm going to try and break this up.

## Maxims

1. *Administrators should not need to install node or npm to run GeoMoose.*
2.  Mapbook's should be shareable among different "UI"s.
3. Easy updates.
4. Recognizing our audience.

## Enumerating useful demos.

1. The "dev" demo is meant to have all the features and demonstrate them in a useful way.
2. The "mobile" demo is a proving case that we can play nice with a UI toolkit. It uses jQuery mobile but that's just a for-example.
3. An "embedded" demo would be super-helpful to demonstrate the ability but we'd need to pick a useful target with which someone was vested.  I think this may be a dedicated separate project but would also be a good candidate for demonstrating how to work without a mapbook or how to work with a mapbook + dynamically configured layers.
4. "Responsive" as a design language this is fading out a bit. But i think it may be appropriate to add some screen size awareness to the primary demo.

## Maintenance

Multiple demos do create a larger surface area for bugs and maintenance.  However, I really think this is a matter of:
1. Testing. The more tests the better.  After we get the initial bulk of tests built up I'd like to add stricter "no test, no merge" discipline to the core dev team.
2. The demos are intended to be *very small* show cases and should continue to work as long as tests for the SDK pass.  Major version changes will require major version change testing.  Integrating all the demos into a single repository may make it easier for Devs to check on them later on.
3. Investment. Investment. Investment.  If a particular demo is important to someone then they're going to make noise. But if we are not seeing uptake or bugs are being released an no one notices then it's very hard to invest our time in it.  

## Services

Services being in "src" was just me trying to find a good place for them.  And they're a little tricky to place because I don't want users to feel like they need to completely re-invent the wheel each time they add data to their application or want to tweak some templates.  Therefore, I put the 'bespoke' services in "src" and have them published in "dist".  I don't think they need to be compiled because seeing the source and the operations is useful.  Better documentation will minimize the need to look at the source but there's a chicken/egg race there.

We could move the services to "demo" if we so chose and I wouldn't feel bad about it. 

## Recognizing our Audience

I think the general "audience" of GeoMoose has wanted to download a zip file, hack at it until it works for them and then let it run.  More advanced members of the audience have wanted to do upgrades and try to adopt new features but have found that progressively difficult as we made major changes and didn't provide a healthy way of upgrading.

That said, I still think having something like the following will make the most sense to those types of users:
```
./geomoose # This is basically the npm package uncompressed
./index.html # The HTML for the demo/app
./app.js # Could be named something else, I'm open minded but it's the main file for the application.
./config.js # Some globals that can be tweaked if app.js is appropriate for the user.  Mainly useful for pointing the application at the demo files. It's not strictly needed.
./mapbook.xml # I have no idea what this is for, but it seemed useful at the time.
```

Then to upgrade, all a user needs to do is replace the `./geomoose`.

If a user wants to start working on the bleeding edge then they replace `./geomoose` with a clone of the gm3 repository.  At that point they'd need to invest in the toolchain (node, npm).  

This is easy and clear instruction.  It doesn't require any tools that  don't come with common operating systems (ZIP, copy, text editor) until the user is REALLY interested in it.

## So what are all those repos for?

1. `geomoose/gm3` is very clearly for us to do the development of the library.  `./demo` is in there as a way for us to quickly and easily test everything.
2. `geomoose/gm3-demo-data` is there to keep a common set of testable layers in a convenient place.  It lets us share data among different test scenarios and prevents us from needing to duplicate it in other places.

What about the rest? Frankly, the repositories are pretty open but in my opinion, they should be nothing more than useful tools for us to publish demos in the fashion listed above.

If a developer wants to include geomoose in their application then they will have the tool chain and appropriate knowledge to do so.  So it's important that we publish `geomooose/gm3` to NPM.  If want to provide an example of using geomoose with NPM, great, it should probably be based on the dev demo and gives minimal instruction. The demos themselves need not be published to NPM.

**Comment by elil** [comment]
Lots going on here.  Generally, it seems that you've captured what I think is a common picture for GeoMoose.  I think that you're heading in the correct direction.  

Finding issues in the tests or demo(s) is better than users finding them in their applications.  

Since we really have two audiences, it should be clear which audience is targeted with which documentation.  i.e. Download, unzip, and configure users should not get (mis)guided down the node, npm route.  

Should we test some of these alternatives and see how they work?

**Comment by klassenjs** [comment]
There is lots to digest there and will take a few readings.

In the mean time, some things to keep in mind:
1) We traditionally provided a parcel application as the (only) demo.  How are we planning to continue to do this?  Is this part of the mission of gm3/demo or is this something that still needs to be built?

2) Using npm/grunt to assemble the demos (vs. shell scripts or Makefiles) means anyone on most platforms can generate the demos the same way we do.  It does not preclude distributing a built version of the demos as a .tgz or a .zip or a MS4W package, nor does it necessarily require a site admin to use npm/grunt locally in the case they want to "copy/paste/replace some shapefiles/edit a mapbook/edit some logos".
(And I am taking it as a given that we want actual dependency management and reproducibility in the maintenance of the demos).

3) I think there should be a smooth process for someone to migrate from the unzip & edit workflow to making some larger tweaks to the demo (adding local features, integrations, getting into JS/HTML, maybe pulling in their own libraries) to full hacking at the GeoMoose core library in a way that their changes can be integrated by the project (full use of npm/grunt/linters/test suites/isolation of site specific and generic code/etc.)  This is mostly going to be related to choosing a good directory layout for the demos and making the "right" way the easy way to do things.  This also relies on the core library being well behaved.

**Comment by theduckylittle** [comment]
I had some noodling on this last night and was considering the following, which I can be more or less convinced is 'good': 

1. Remove `./demo` from `geomoose/gm3`.  Move it to `geomoose/gm3-demos/dev`, I'm also amenable to something like `geomoose/gm3-demos/desktop` or `geomoose/gm3-examples/dev`.
2. Rename `test.html` to `debug.html` as that is a more accurate description of why that HTML file exists.
3. `test.js` becomes `app.js`.

Cloning/downloading `geomoose/gm3-demos/` won't get you anything functional.  It's then up to the user to grab GeoMoose by the most appropriate m eans for their skillset:

* Startup for devs:
```
  git clone geomoose/gm3
  cd gm3
  npm install
  grunt build
  glt clone geomoose/gm3-demo-data
  # "Magic to startup the docker instance here"
  git clone geomoose/gm3-demos
  cd gm3-demos/desktop
  ln -s ../../gm3 ./geomoose # or one could've just cloned in here, we would setup the gm3-demo-data .gitignore to just ignore "./geomoose" directories.
  npm install # installs a small web-proxying server.
  npm serve  # starts up a small webserver with a proxy to the demo data enabled.
 # And in another term...
 cd gm3
 npm install
 grunt build
 grunt watch # will do dynamic rebuilds w/ webpack.
```
*  Startup for non-devs (UNIX demo environment):
```
wget geomoose-demo-data.zip
wget geomoose-desktop-demo.zip
# apt-get install mapserver ?
# apt-get install apache ? nginx ?
# configure apache ? nginx ?
# 2. ?
# 3. Profit
```
* Transition Phase: Let's imagine a world in which they've hacked at a bunch of stuff... so now they have `/srv/geomoose/` and `index.html` and friends are all customized nicely. To transition to hacking on geomoose core...
```
cd /srv/geomoose
rm -rf geomoose
git clone my-fork/gm3 ./geomoose
cd geomoose
npm install
grunt build
```
* Packaging, this may need some revisions to use npm based tools but in general the make file itself would be pretty simple:
```
cd $GM3_DIR
git checkout @version
cd $DEMO_DIR
git checkout @version
# copy in "./geomoose"
# kick out zip file...
```

This work flow is:
A. Slightly less convenient for dev'ing than keeping the "dev demo" in the main repository. But it does "standardize" a workflow and forces dev'ing on the demos will use the right code during development. We don't lose the dynamic rebuilding (grunt watch will handle that) but lose the nicely integrated server.
B. Relatively easy to package.
C. Silly easy to document going from "copy and paste" to "dev'ing now".

**Comment by theduckylittle** [comment]
After a lot of consternation this week, there's been some development in how we're doing this.  The good news is that neither Jim nor I full 100% like the solution which means we've probably reached some sort of workable compromise.

We *are not* having a separate repository for the example applications. It was too easy for the examples to diverge from the code base and as we start developing the tests; it's much easier to have the examples and the base code in the same spot.  All the example code is in `/examples/[example name]/`.

We're still evolving how we're going to package the stuff (I wrote some quicky bash scripts that could use some refinement) but we are moving forward on being able to hand off ZIP files for administrators to install and start hacking against.

**Comment by klassenjs** [comment]
The main pro I see for the one repo solution is issues and docs are also in
one spot which will be much less confusing for people starting with the
project.

On May 13, 2017 8:28 AM, "theduckylittle" <notifications@github.com> wrote:

After a lot of consternation this week, there's been some development in
how we're doing this. The good news is that neither Jim nor I full 100%
like the solution which means we've probably reached some sort of workable
compromise.

We *are not* having a separate repository for the example applications. It
was too easy for the examples to diverge from the code base and as we start
developing the tests; it's much easier to have the examples and the base
code in the same spot. All the example code is in /examples/[example name]/.

We're still evolving how we're going to package the stuff (I wrote some
quicky bash scripts that could use some refinement) but we are moving
forward on being able to hand off ZIP files for administrators to install
and start hacking against.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/geomoose/gm3/issues/27#issuecomment-301248382>, or mute
the thread
