### ISSUE TITLE
Select results grid does not work following identify

### ISSUE THREAD

**Issue by elil** [geomoose/gm3#287]
Open demo
Identify a parcel
Select parcel(s)
Hit "Go"
Get Super Tab that says, "Parcel selection results are shown in the results grid. "
There is no results grid, expect results grid at bottom of page.

**Comment by klassenjs** [comment]
Confused:  If I use the Identify tool, the results show up in the Super Tab as soon as I click on a parcel.  (Note: if I click "Go" without clicking on a parcel some strange stuff happens that probably deserves it's own issue).

If I use the Select Features tool to select a parcel, I see the message you indicated in the Super Tab, but also get a results grid at the bottom of the page.

If I use the Select Features tool and create a selection that doesn't select any parcels, it does what you said (and also says 0 features were returned in the Super Tab).

**Comment by klassenjs** [comment]
Ok, Got it.

1) Click Identify Tool
2) Click on a parcel (Super Tab shows results of identify as expected)
3) Click Select Features Tool
4) Draw selection of a parcel(s) on map, and click "Go"
5) Results in N features selected in Super Tab, Selected Parcels highlighted on map, but no results grid.

**Comment by tchaddad** [comment]
Eli's combo only occurs if Select is not the first tool run. 

I ran into it as well, but was doubly confused because in other instances, the results would be provided in the table, but the table would just be minimized, and I didn't realize it:

![results_collapsed](https://user-images.githubusercontent.com/1042618/37178460-6c1e3a84-22d7-11e8-8010-72bb520757ac.PNG)

Could the problem be similar in this case, except with the collapse icon not even drawing to indicate the table is there?

**Comment by klassenjs** [comment]
Note: The identify creates an error in the console about:  ```l.templates.gridColumns is undefined```

**Comment by theduckylittle** [comment]
I believe this is fixed as fall-out from fixing identify:
- https://github.com/geomoose/gm3/pull/292

**Comment by klassenjs** [comment]
#292 fixed this for me.  @elil?

**Comment by elil** [comment]
Yes, appears fixed.  Thanks.
