### ISSUE TITLE
Select Features on Drawing and Markup layer

### ISSUE THREAD

**Issue by klassenjs** [geomoose/gm3#302]
Should we, shouldn't we?  It seems inconsistent with Identify that it currently doesn't.

**Comment by tchaddad** [comment]
Just bumped into this today, while testing the demo...

Wanted to say that whatever you decide, "Drawing and Markup" should not be the top option in the select drop-down, because it is too easy for the user to not see that choice, and to have them hit "Go" and get no results, and then think that select is broken.

**Comment by klassenjs** [comment]
The user will have to select a layer... maybe we need to make that more obvious.

**Comment by tchaddad** [comment]
Yeah, one way to make it more obvious is to put it first in the set of select options, as in:

Select from_______ using point/line/polygon, with _____ buffer

But even if you do this re-ordering, I think that for the demo itself, Parcels should be the default selected in the drop-down, as it is just too easy for the user to hit "Go" with the drawing default selected, and then they will get nothing, and think the demo is broken.

**Comment by theduckylittle** [comment]
The core of this ticket was  released in 3.3.0.  ref: #397  for the follow up work.
