### ISSUE TITLE
Does not load in Internet Explorer or Edge

### ISSUE THREAD

**Issue by mjreynolds** [geomoose/gm3#309]
Tested the demo site at https://demo.geomoose.org/master/desktop/ in IE 11 and Edge on multiple Windows 10 desktops and multiple networks.

IE 11 Developer Tools Console reports the following:
SCRIPT438: Object doesn't support property or method 'fill'
geomoose.min.js (27,684273)
SCRIPT5009: 'gm3' is undefined
app.js (32,1)

Edge Developer Tools Console reports the following:
SCRIPT438: Object doesn't support property or method 'ToString'
geomoose.min.js (33,1634)

Perhaps a polyfill solution?

**Comment by klassenjs** [comment]
Huh, testing demo.geomoose.org: Edge works for me, but IE 11 fails as you say.

**Comment by mjreynolds** [comment]
I do see that in Edge 42.17134.1.0/EdgeHTML 17.17134 it loads and works.
It fails in Edge 38.14393.1066.0/EdgeHTML 14.14393.

Honestly our interest isn't in Edge especially if a newer version of Edge does work with Geomoose.

IE 11 is a difficulty for us though.

**Comment by klassenjs** [comment]
Testing IE11.0.9600.19035:
- v3.0.0 works (from zip - can't build because npm is super awesome)
- v3.1.0 works (from zip - can't build because npm is super awesome)
- v3.1.1 works (from git)
- v3.2.0 fails (from git)
- master fails

The thing is I don't see a change in our code that seems to fit the error between v3.1.1 and v3.2.0 (although without sourcemaps working in IE it is hard to tell) which makes me worried it has to do with a dependency.

**Comment by klassenjs** [comment]
Following commits back:
- 86fca31a "Merge Branch fix-build" fails
- 18e316c "Fix all the build issues" fails 
- 7478293 is v3.1.1 works

I'm afraid I am stuck and out of time.  @theduckylittle, Ideas?

**Comment by theduckylittle** [comment]
I believe this was related to the lack of `babel-polyfill`.  With the next release, I'm going to work on some basic browser-stack style testing utilities.

**Comment by theduckylittle** [comment]
This got done! We now have browser stack.
