### ISSUE TITLE
Scalebars seem Incorrect

### ISSUE THREAD

**Issue by tchaddad** [geomoose/gm3#361]
I might be crazy, but the scalebars in the demo seem to be shorter than then should be by about 25%.

This can be confirmed by measuring against a feature of known length, or even using the measure tool, which by comparison to known data, is pretty accurate

**Comment by theduckylittle** [comment]
I can verify the behaviour on master.

**Comment by theduckylittle** [comment]
Hm... looks like GeoMoose is passing the correct values to MapServer...

**Comment by klassenjs** [comment]
It doesn't happen to be wrong by cos(latitude) does it?  (.707 at 45°)

**Comment by tchaddad** [comment]
I wondered the same thing. 

Or possibly that what is being passed is not being passed with enough decimal values (if the math is being done in 4326).

**Comment by theduckylittle** [comment]
I think it might be a technique issue. GeoMoose is doing projection to valid measurement projections whereas I believe MapServer may be actually just blindly using EPSG:3857.

**Comment by theduckylittle** [comment]
I'm leaving this open despite the PR...

**Comment by tchaddad** [comment]
Relevant thread: https://lists.osgeo.org/pipermail/mapserver-users/2018-January/080474.html

**Comment by tchaddad** [comment]
Would using OpenLayers to add the scalebar be a future enhancement option?

https://openlayers.org/en/latest/examples/scale-line.html

**Comment by klassenjs** [comment]
I suspect that MapServer is treating the X,Y of 3857 as literal meters when it generates the scalebar.  IIRC the scalebar is controlled by the `MAP->UNITS` setting [1] and not by the actual projection definition.  This is more-or-less correct in reasonably behaved local projections (and is correct in an equal area projection), but is a bad assumption in a Mercator projection.

[1] From https://mapserver.org/mapfile/map.html
> UNITS [dd|feet|inches|kilometers|meters|miles|nauticalmiles]
>    Units of the map coordinates. Used for scalebar and scale computations. Nauticalmiles was added in MapServer 5.6.

**Comment by theduckylittle** [comment]
@tchaddad - We avoided using the scaleline control in the past because it doesn't print well... but it's definitely worth researching.

**Comment by klassenjs** [comment]
Is that still an issue with GM3?

**Comment by theduckylittle** [comment]
Yes it is. The scaleline is still rendered as DOM and not as a graphic on the map. So when we scrape the map-canvas for a picture we would still need to render the scaleline our selves.

**Comment by tchaddad** [comment]
We definitely have users who are interested in having a valid scalebar, at least on screen. Maybe we can separate implementing scaleline, and printing scaleline into separate issues for future enhancements?

**Comment by klassenjs** [comment]
Maybe I'm too old school, but I would argue a valid scalebar is a requirement for any proper map.  Anything less is at best a pretty picture.

And because I feel like ranting about coordinate systems and correctness...

The more I have been looking at "fixing" 3857 for use with local precision mapping, the more it seems like a bad idea.  It's an inappropriate projection for local use applied on an ellipsoid that is half treated as a sphere (and the ellipsoid isn't even the right one for most local use in North America.  And as far as I can tell, that transformation is never applied in practice).  At best 3857 is a messy compromise to more quickly deal with world-wide datasets.  At worst it is a hand-wavy, ill-defined approximation that doesn't make a lot of sense.

As an example of the problems all this causes:

Measuring the distances around a random section (ideally a square mile) I get different results between GeoMoose 2.9.2 and GeoMoose 3.2.2.  All measurements were taken fully zoomed in.  Both versions are accessing the same mapfile, 2.9.2 in county coordinates, 3.2.2 in EPSG:3857. All numbers reported are county coordinates/us-ft.

```
|          |   2.9.2 |   3.2.2 |
|----------+---------+---------|
| Length 1 | 5271.26 | 5269.14 |
| Length 2 | 5273.18 | 5271.06 |
| Length 3 | 5226.37 | 5224.29 |
| Length 4 | 5252.36 | 5250.24 |
```

Looking closer at Length 1, both versions report the endpoints as:
`(576936, 157527)` and `(582207, 157583)`

The actual endpoints from survey monuments are `(576936.065, 157527.116)` and `(582207.245, 157582.750)` so both versions of GeoMoose (and MapServer) are getting this part right.

This gives a difference (dx,dy) of `(5271, 56)` for a total distance of `5271.3`.  So it isn't just scalebars... GeoMoose 3.2.2 (EPSG:3857) is getting measurements wrong too.  (I can't easily test this, but it wouldn't surprise me if GeoMoose 2.9 was also incorrect in EPSG:3857).

Note: this difference is a couple of orders of magnitude larger than could be explained by the difference between international feet vs. us-survey-feet.

Now, someone explain to me again why we should settle on all the maps being wrong because some pseudo-freely available basemaps did it that way.

**Comment by tchaddad** [comment]
So, I agree about needing a functional scalebar, especially if one is available via openlayers for onscreen display. We can spin of a printable scalebar into a separate issue.

But I actually haven't had a problem with measurement. I can't confirm with the demo because I don't know the dimensions of those parcels, but using local parcel data where I can label the edges of the polygons with the lot dimensions, measure is pretty spot on for me. 

What does not work for me is buffer distance. If I draw a polygon around a parcel of known dimensions, and then buffer that shape, the buffer is showing the same failing of the scalebar - it's about 25-30% less wide than it should be. So buffer seems to be using 3857 units?

I'll have to rustle up some screenshots and open up another buffer issue showing that

**Comment by theduckylittle** [comment]
Fixed the buffer issue. And I believe #398 will cover the ground lost by dropping the scalebars.
