### ISSUE TITLE
Config.js

### ISSUE THREAD

**Issue by descholive** [geomoose/gm3#440]
Hello

I want to place my ".map" in another place that ms4w\apps\gm3-demo-data\demo

but when i change config.js ('/ms4w/apps/gm3-demo-data'), there is a problem of layer legend

can you help me ?

THKS

**Comment by theduckylittle** [comment]
We will need more help from you!

Did you move all your mapfiles to the new parent directory?

Can you use the developer tools to check for the legend request and post
the results?

Thanks!

**Comment by descholive** [comment]
thks for the answer,

yes il move all mapfiles

what is the developper tools ?

TY

**Comment by descholive** [comment]
in config.js we have "mapfile_root: '/ms4w/apps/gm3-demo-data'"
in my mapbook, i have this : ./demo/pipelines/departement.map (my layer is departement.shp)

if i change the location of the mapfile, that doesnt work....

**Comment by klassenjs** [comment]
I can't tell what exactly you changed or what exactly the error is from your description.

1) GeoMoose just puts mapfile_root and the path in the mapfile together to tell MapServer where to find the mapfile.  

So from what you said above:
/ms4w/apps/gm3-demo-data/demo/pipelines/departement.map

Since you are on Windows, it will look on the same drive as ms4w is installed.  I'm not sure what to do if your data is on a different drive.

2) In the demo mapfiles we use includes to avoid duplicating common sections of the mapfile in each mapfile.  geomoose-globals.map is one of these and one of the things it tells MapServer is where it can find it's fonts and symbols.  All of these files need to be in the same place relative to each other for the default paths to the included files and the fonts and symbols to work.  If you are moving things around, you likely broke this relationship.

3) We need to see the error message MapServer is likely returning to give you more advise on what is wrong.  There are two places this might show up.  One is in the apache error.log.  The other (and generally easiest) is in the web browser developer tools (usually accessible via F12).  In the developer tools' network tab you should be able to see the requests GeoMoose is making to MapServer.  Find the GetMap request for the layer that is failing and right click on it and select open in new tab.  You will likely see a text error message from MapServer.  Sometimes it will insist on downloading the error message to a file first and the you can open the file in a text editor to see the error message.

**Comment by tchaddad** [comment]
@descholive this is a perfect question and discussion to have on the Geomoose-users email list, so that more people can see you question and be helpful.

You said your problem is with the legend, when you move your map file to a new location. 

Most likely this is because you need to edit your mapfile to adjust the path at the top that points to the geomoose_globals.map file. 

If your mapfile cannot find geomoose_globals.map, and that file contains the legend definition, that that could be your problem.

**Comment by descholive** [comment]
thank you all for the answers...
i ll try 

have a good day
