### ISSUE TITLE
demo could benefit from multiple="false" (radio buttons) in catalog

### ISSUE THREAD

**Issue by elil** [geomoose/gm3#449]
Right now the demo lets users add multiple basemap layers at a time, while this could be useful in the case of transparency, the more common case will be inefficiencies with multiple basemaps on and confusion over why the desired layer is not displaying.  

Looking at #351, this has come up before.  Do we want to look at it again?  Maybe a restricted option for 1:1 cases.  Maybe we could come up with a mapbook validator that would check things like this?

**Comment by bblammo** [comment]
hmm, this is an interesting one.

We've run into this from time to time, butnit hasn't really been a big
deficiency because we have a smaller and faurly static user group.  I can
see thisnbeing more of a problem with occasional use.

What about using some sort of status bar with circles and numbers inside
indicating hiw many of which type of layer are on/active.

alt tags for describing what each number represents.

bobb

**Comment by chughes-lincoln** [comment]
I think when start having larger user groups that aren't as accustomed to GIS it will become more of an issue. Right now our site has several high resolution imagery layers plus a couple lidar hillshades which will use a lot of resources if users don't know to turn off one layer to switch to a layer below it (plus the inconvenience of not being able to click once to choose which 'basemap' layer you want)

**Comment by theduckylittle** [comment]
refs: PR #451

**Comment by elil** [comment]
Radio buttons appear to work in the demo, closing.
