### ISSUE TITLE
Buffered Selection

### ISSUE THREAD

**Issue by theduckylittle** [geomoose/gm3#48]
User's will want to be able to select features using a drawn geometry and a buffer.  They also want to select features from a layer, buffer those features, and select a set of features.  

The classic example: Buffer a parcel by 1,000 feet.

To do this, we're looking to use JSTS.  This is a big library and adds a lot to the deliverable size.  Care should be given to prevent the library from bloating much more.  Making JSTS optional may need to be on the table for folks who won't need the buffering functionality.

**Comment by elil** [comment]
I've never understood the draw geometry and buffer option.  What is the purpose?  Why not just draw it bigger to begin with and not buffer it?  (buffering a line sort of makes sense).  

I understand the purpose of the select a geometry (or set of) from a layer and buffer it.

**Comment by klassenjs** [comment]
Usually because you need to notify people within a certain distance of a
project area.

It might be more ideal to upload that geometry or select it from another
layer, but people don't always have it ahead of time.

On May 16, 2017 14:59, "Eli L Adam" <notifications@github.com> wrote:

I've never understood the draw geometry and buffer option. What is the
purpose? Why not just draw it bigger to begin with and not buffer it?
(buffering a line sort of makes sense).

I understand the purpose of the select a geometry (or set of) from a layer
and buffer it.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/geomoose/gm3/issues/48#issuecomment-301897842>, or mute
the thread

**Comment by theduckylittle** [comment]
PR merged, follow up tickets filed, this ticket can party on in closed statuis.

**Comment by theduckylittle** [comment]
Option 2 can happen when you choose to buffer the results.
