### ISSUE TITLE
pass thru additional parameters for AGS map-source

### ISSUE THREAD

**Issue by brentfraser** [geomoose/gm3#517]
Currently (v3.6.1) only `<param name="cross-origin" ` is passed along from the mapbook.xml to create the AGS layer.  It would be nice to pass other AGS-valid parameters, and custom parameters as well.  Related to #475

**Comment by brentfraser** [comment]
FYI, currently in the demo the request made is 
```
https://services.arcgisonline.com/ArcGIS/rest/services/NatGeo_World_Map/MapServer/export?
F=image
FORMAT=PNG32
TRANSPARENT=true
SIZE=256,256
BBOX=-10353854.103396835,5545047.7799198255,-10351408.11849171,5547493.764824951
BBOXSR=3857
IMAGESR=3857
DPI=90
```
The SR definitions of 3857 is curious since the demo is 26915

**Comment by brentfraser** [comment]
So I made the following change in ags.js:

```
    return {
        crossOrigin: cx_origin,
        params: mapSource.params,
        url: mapSource.urls[0]
    }
```
by adding the `params: mapSource.params,` and it looks like the mapbook.xml params abeing passed along.

**Comment by tchaddad** [comment]
Thanks Brent - I will give that a try on my end to see if it solves the issue I was dealing with in #475

**Comment by theduckylittle** [comment]
Added this in PR #534 

It may be worthwhile to have a different target AGS server. If folks really want us to test this more deeply. A lot of the AGS functionality came along as "Oh wow! It works!" and could use substantial hardening from folks who work with it on the regular.

**Comment by brentfraser** [comment]
I agree.  I find the whole AGS ecosystem confusing, and the GeoMoose nomenclature doesn't help.

- type="ags" means an ArcGIS Image Server (/MapServer/) accepting image requests
- type="ags-vector" means an ArcGIS Image Server (/MapServer/) accepting feature query requests, NOT an ArcGIS Feature Server.

I really need to make a table of servers and GM supported requests.

**Comment by bfischer-hei** [comment]
It get’s more complicated than this with all of the parameters within each type.  I just happened to catch one things though that I think is wrong in this ticket.

type=”ags-vector” does not mean ArcGIS Imager Server rather it should meant ArcGIS Feature Service.

Not sure if this helps or confusing things more but I’ll throw it out there anyway.

Here’s an exhaustive list of types of services you can publish with ArcGIS Server (now called ArcGIS Enterprise).  Services published with ArcGIS Online is a subset of these.  The confusing part in my opinion is because there are so many options built into each service endpoint.  https://developers.arcgis.com/rest/services-reference/resource-hierarchy-services-.htm

For integration (consuming with GeoMoose).  In my opinion I would focus on these 3 types.  I think they will be by far the most useful.


 1.  Feature Service (https://developers.arcgis.com/rest/services-reference/feature-service.htm) – most similar to a WFS services, sends the vector features and attributes to the browser.
 2.  Map Service (https://developers.arcgis.com/rest/services-reference/map-service.htm) – most similar to WMS/WMST services, sends an image back to the browser.   This is probably the most complicated one because you can have sub-layers to a MapService that you can specifically pass in and it will only return that sub layer.  Similar to a WMS service is you only want to get an image back with one layer in a WMS service that has multiple layers.  The difference is ESRI only uses id’s for those sublayers and you can not use sub layer names in the requests.
 3.  Image Service (https://developers.arcgis.com/rest/services-reference/image-service.htm) – similar to WMS/WMST but opens up more raster/image processing options.  Most commonly used to serve out large collections of aerial imagery.

On all these service types you will need to decide if you only support rending the maps/features or if you will also support querying.

A future AGS type could be Vector Tile Service (https://developers.arcgis.com/rest/services-reference/vector-tile-service.htm).  Just starting to become more popular.

In my opinion I would map GeoMoose type’s to AGS in this way.

 *   type="ags-map" means an ArcGIS Map Service
 *   type="ags-feature" means an ArcGIS Feature Service
 *   type="ags-image" means an ArcGIS Image Service
 *   type="ags-vectortile" means an ArcGIS Vector Tile Service


        Brian Fischer
Project Manager - GIS | Vice President
Houston Engineering, Inc.
O 763.493.4522 | D 763.493.6664 | C 763.229.2734
        [cid:hei_d562a228-8e53-424d-8c69-43b1a222b74e.png]      7550 Meridian Circle North, Suite 120
Maple Grove, MN • 55369
www.houstoneng.com<http://www.houstoneng.com/>
Follow us: Facebook<https://www.facebook.com/houstoneng> | Twitter<https://twitter.com/houstoneng> | LinkedIn<https://www.linkedin.com/company/houston-engineering-inc.> | YouTube<https://www.youtube.com/user/HoustonEngInc>

This entire message (including all forwards and replies) and any attachments are for the sole use of the intended recipient(s) and may contain proprietary, confidential, trade secret, work-product, attorney-client or privileged information. Any unauthorized review, use, disclosure or distribution is prohibited and may be a violation of law. If you are not the intended recipient, please contact the sender by reply email and destroy all copies of the original message.

**Comment by brentfraser** [comment]
I think the solution is for us to document what GM supports as of now, add other protocols as needed.  And for extra credit, find some public servers and add tests, or at least add a "kitchen-sink" demo to the examples.
