### ISSUE TITLE
Document "loc=..." parameter in URL

### ISSUE THREAD

**Issue by chughes-lincoln** [geomoose/gm3#600]
The extent of the map window is determined by a 'loc' parameter that includes a resolution component, as well as a center of map x/y point.

Some documentation of how this parameter is created at a given location would be useful for creating links to specific locations.

**Comment by tchaddad** [comment]
The demo opens for me at:
loc=38.21851414258813;-10370523.762301365;5550954.22762416

where:

- **meters per pixel** = 38.21851414258813 (equivalent to Zoom level 12)
- **x** = -10370523.762301365
- **y** = 5550954.22762416

The number of decimals displayed above for the first parameter is probably excessive, since this is just for zooming to an extent. 

This table has a "meters per pixel" column for the equator, that show rough scales and Zoom level equivalents:
https://wiki.openstreetmap.org/wiki/Zoom_levels

If you round those values meters per pixel values from the table to just one decimal place, the extent that the map opens up at is effectively the same at the latitude of the demo, and I guess would be fine for a map that is only displaying fixed zoom levels.

**Comment by klassenjs** [comment]
See #644

**Comment by theduckylittle** [comment]
Closing as documented?
