### ISSUE TITLE
Table performance

### ISSUE THREAD

**Issue by brentfraser** [geomoose/gm3#602]
While continuing my testing of  the identify, select, and search workflows, I've noticed the **slow performance** in retrieving the data when selecting all the parcels in our demo data set.  Not too surprising as the select returns over 4000 parcels with geometry (in a text format).

As far as I know the geometry is using only for highlighting (and "hot" highlighting on row mouse-overs) so I wonder if an option to use a bounding box for highlighting would improve performance?  But it might be a little goofy on diagonal line features for example.  Or an option for no geometry (so no highlighting)?  Or ask the server to generate a highlight image (for wms and ags)?

Or have an admin settable limit for the number of features to select (say 10,000?) and show a warning to the user to select fewer features.  That might be weird dealing with Search results.

Or maybe do table "paging" like jquery UI datatables and only retrieve the geometry for the features on the current page.

**Comment by elil** [comment]
On Fri, Aug 28, 2020 at 8:43 AM Brent Fraser <notifications@github.com>
wrote:

> As far as I know the geometry is using only for highlighting (and "hot"
> highlighting on row mouse-overs) so I wonder if an option to use a bounding
> box for highlighting would improve performance? But it might be a little
> goofy on diagonal line features for example. Or an option for no geometry
> (so no highlighting)? Or ask the server to generate a highlight image (for
> wms and ags)?


No highlighting would remove much of the usefulness.  Indexing can get
complicated and would do nothing for the "everything" selection.  Most of
the time, I think that people would be working with everything in the
selection so indexing would not improve anything in those case.


> Or have an admin settable limit for the number of features to select (say
> 10,000?) and show a warning to the user to select fewer features. That
> might be weird dealing with Search results.
>

A configurable limit that throws a warning would be a good idea.


> Or maybe do table "paging" like jquery UI datatables and only retrieve the
> geometry for the features on the current page.
>

Paging could be weird for working with a selection set.  What you see on
the map would change with every "page."

**Comment by brentfraser** [comment]
Another  option is to show a progress indicator.

And maybe doing nothing about this is OK.

**Comment by brentfraser** [comment]
I think both.  But maybe my machine was sluggish that day.  Using Chrome to connect to the demo at geomoose.org, and selecting all 4,040 parcels, the results take six seconds to load into the table and highlight.  And yes after loading pan and zoom out seem a little slow, but still usable.  

I wonder what would happen if the parcel layer had 20,000 parcels?

**Comment by chughes-lincoln** [comment]
A query of around 20,000+ parcels on my server performs relatively well. It takes a while to load (although a similar query on my old geomoose 2 server times out before it finishes), but scrolling through and sorting the tab and table is pretty smooth (as long as highlight isn't set up). Navigating the map with all of the selected geometries is almost prohibitively slow however (zooming to individual results, or zooming pre-configured locations seems to work eventually, but not panning around the map). I'm not sure how much of that depends on the server or the client.

In terms of the table performance, the admin could also potentially configure results to highlight on click rather than hover (i.e. onclick="app.clearHighlight(); app.highlightFeatures({'ID' : '{{ properties.ID }}'}, true)"). I'm not sure how less useful that would be to the user than on hovering.

**Comment by theduckylittle** [comment]
Two major changes that should make this not a problem in 3.11.0:

1. There is no more 3x-multiplication of the feature set in memory. Nor do we keep a running log of multiple query results. The map, list, and table all use the same list of features but render them differently.
2. The table/grid has now been 'virtualized' making is so that only the rows that are visible are rendered. This *really* speeds up the table rendering with large datasets.
