### ISSUE TITLE
Grid: numbers are not sorted as expected

### ISSUE THREAD

**Issue by robinrullo** [geomoose/gm3#672]
I didn't notice it right away but `Intl.Collator` doesn't sort number as expected.
As an exemple:
```js
console.log(['1', '50', '100', '70', '600'].sort(new Intl.Collator().compare));
// output: ["1", "100", "50", "600", "70"]
// expected: ["1", "50", "70", "100", "600"]
```
therefore the sorting in the grid is not performed correctly.
When type is number, it should still simply compare `a > b`

EDIT: Use `numeric: true` may do the trick
```js
new Intl.Collator(undefined, {numeric: true})
```

**Comment by klassenjs** [comment]
I think this is already fixed.  See commits e013a243 and 6f33eae5

**Comment by robinrullo** [comment]
I opened #663 wich is merged and fixed special characters sorting (and works fine).

But now I'm using the sortResults function from https://github.com/geomoose/gm3/commit/6f33eae54a0a1f9777e2f8745ed5661450a3fe67 with `Intl.Collator()` , I'm getting that:
![image](https://user-images.githubusercontent.com/25304220/127052544-2e8f33ff-46f8-4ee7-8461-f8034829a396.png)

Grid columns template:
```json
{
  "title" : "NUMERO",
  "property" : "NUMERO",
  "sortAs": "number"
}
```

The new sort function (`Intl.Collator()`) works like that:
- **21** is **2** and **1**.
-  **2** < **8**
- conclusion: **21** < **8** 

I tried to add `numeric: true` option to use numeric collator and fixed that.
```js
const collator = Intl.Collator(undefined, {numeric: true});
```
(using undefined locales to take browser locales)

**Comment by klassenjs** [comment]
My point is it shouldn't even be hitting the Intl.Collator code path for numeric values.

If you look at the changes between 717c7fd and 6f33eae on issue #663 (which unfortunately is not in the git history of the main branch due to being squashed in a rebase), this was noted and fixed and it currently works properly in the demo for the "Est. Value" column on the Parcels layer.

![image](https://user-images.githubusercontent.com/165622/127066382-9e1d2e0d-8146-47af-9716-1fc18b7929f4.png)

**Comment by robinrullo** [comment]
oh yes, sorry, I missed it.
