### ISSUE TITLE
Add support for FeatureInfo on on Map Source type="ags" layers

### ISSUE THREAD

**Issue by tchaddad** [geomoose/gm3#747]
Map Source type="ags" is a common service type that can support queries, but GM does not currently support the query option on this type of service

According to previous discussion on #730 this is a known missing support, but may be an easy addition. The service type is quite common, and so adding this support would be super helpful.

**Comment by tchaddad** [comment]
This example of "ags-polygons" is used in the demo mapbook-test-servers.xml mapbook:
https://gis2.co.dakota.mn.us/arcgis/rest/services/DCGIS_OL_Transportation/MapServer/21

You can find the map source block config for this by searching for `<map-source name="ags-polygons"  type="ags">` in the test-servers mapbook:

https://github.com/geomoose/gm3/blob/main/examples/desktop/mapbook-test-servers.xml

**Comment by brentfraser** [comment]
Would be nice.  For those interested try to do an identify on the airstrip polygon in the center of this map:
https://demo.geomoose.org/3.x/desktop/?mapbook=test#on=ags-polygons/runways;openstreetmap/osm_mapnik&loc=4.9003;-10377960.57;5562838.67

**Comment by brentfraser** [comment]
A note on the "ags" protocol (so when I revisit this next year I won't need to re-research this).

ESRI _does_ allow an Identify on the ags raster service.  Instead of doing a /Mapserver/export, you do a /Mapserver/identify.  See Example 3 at https://developers.arcgis.com/rest/services-reference/enterprise/identify-map-service-.htm  The specific layer ("2") is selected by the parameter `&layers=all:2` (to display a layer we currently use `<param name="layers" value="show:2" />`).  The request also requires tolerance, mapExtent, and imageDisplay (e.g. size).  We'd likely have to write a specific method to construct and execute this query.

As an alternative to the above ESRI Identify method, I tried our "query-as" route.  I made a couple of minor code changes to enable queries on a mapsource type of 'ags':
```
diff --git a/src/gm3/actions/mapSource.js b/src/gm3/actions/mapSource.js
index 8c4a05b..85d17c9 100644
--- a/src/gm3/actions/mapSource.js
+++ b/src/gm3/actions/mapSource.js
@@ -517,6 +517,7 @@ function isQueryable(mapSource) {
     }
     // check by type
     switch(mapSource.type) {
+        case 'ags':
         case 'wms':
         case 'wfs':
         case 'ags-vector':

diff --git a/src/gm3/actions/query.js b/src/gm3/actions/query.js
index e00bee3..7b411e4 100644
--- a/src/gm3/actions/query.js
+++ b/src/gm3/actions/query.js
@@ -57,6 +57,7 @@ export const runQuery = createAsyncThunk('query/run', (arg, {getState, dispatch}
                 return wmsGetFeatureInfoQuery(layer, state.map, mapSource, queryDef);
             case 'wfs':
                 return wfsGetFeatureQuery(layer, state.map, mapSource, queryDef);
+            case 'ags':
             case 'ags-vector':
                 return agsFeatureQuery(layer, state.map, mapSource, queryDef);
             case 'geojson':

```


I then added a layer for querying and referenced it in the layer for display:

```
    <!-- - - - - - - -  TYPE = "ags"   - - - - - - - - - -->
    <map-source name="ags-polygons"           type="ags">
        <url>https://gis2.co.dakota.mn.us/arcgis/rest/services/DCGIS_OL_Transportation/MapServer/export</url>
        <param name="cross-origin" value="anonymous"/>
        <layer name="runways" title="Runways" query-as="ags-polygons-query/runways">
            <param name="layers" value="show:21" />
        </layer>
    </map-source>

    <map-source name="ags-polygons-query"           type="ags">
        <url>https://gis2.co.dakota.mn.us/arcgis/rest/services/DCGIS_OL_Transportation/MapServer/21</url>
        <config name="pixel-tolerance" value="2" />
        <param name="cross-origin" value="anonymous"/>
        <layer name="runways" >
            <template name="identify" auto="true" />
        </layer>
    </map-source>

```
Note the slightly different URLs.

It seems to work fine:
![image](https://user-images.githubusercontent.com/1638313/207679951-302edd0a-2ff7-41c3-9666-8ac2c010dfbd.png)

I'm not sure I like the use of query-as method over writing a separate function in GeoMoose.  I have yet to test the Select and Search operations with this method...

**Comment by brentfraser** [comment]
For symmetry, I removed the change to query.js and now have: 
```
<map-source name="ags-polygons"           type="ags">
:

<map-source name="ags-polygons-query" type="ags-vector">
:
```

And I've tested the Select and Search functions and they seem to work.

**Comment by tchaddad** [comment]
This is exciting @brentfraser! I haven't yet had a chance to try it locally, but glad it doesn't look too complicated to add. I see a ton of these services in the wild, and enabling query is a really nice option...

**Comment by brentfraser** [comment]
Test with #775

**Comment by tchaddad** [comment]
Working in 3.12!
