### ISSUE TITLE
Measure - Bearing Accuracy

### ISSUE THREAD

**Issue by chughes-lincoln** [geomoose/gm3#832]
It looks like the logic for how Bearing is calculated has changed between 3.10 and the current beta (perhaps with https://github.com/geomoose/gm3/pull/799).

See screenshot of the demo using the 1km grid:
![image](https://user-images.githubusercontent.com/43766648/236878635-1f3a11cc-9a75-4371-9051-63775ecacf7e.png)

The bearings should be 45 degrees, not 54. I tested a similar grid on my site, and the bearings are correct on 3.10.

**Comment by theduckylittle** [comment]
Did a little digging in, this is a projection issue...

- The map is displaying 3857 (all these are EPSG code references...)
- GM3.10 stored measure distances as 3857 then reprojected to UTM for Measurement.
- GM3.11 stores distances as 4326. UTM is used for length but now 4326 instead of 3857 is being used for the bearing calculation. Arguably, that is the "true" bearing, but this is a difference in behavior between versions.

**Comment by elil** [comment]
I think bearing in UTM (or some other local grid) is appropriate.  Same as distance.  The "usual suspects" like 4326 and 3857 can all cause problems (unless the underlying library is already doing tricks to account for this- see also PostGIS geography, https://postgis.net/docs/manual-3.3/using_postgis_dbmanagement.html#PostGIS_Geography).

Selection of UTM zone (or some other local grid) being appropriate is mostly true for "local" work which I think most GeoMoose sites are aimed at.  If making a site for worldwide great circle distances and bearings, then a different approach is probably needed (see again PostGIS geography data type and functions, https://postgis.net/docs/manual-3.3/using_postgis_dbmanagement.html#PostGIS_GeographyVSGeometry)

4326 "bearings" are mostly a function of latitude.  See this correct example in Quito (on behalf of the 0 degrees latitude):

![image](https://github.com/geomoose/gm3/assets/5263258/9d6a3874-1c9b-44c5-a280-db1a56d3d7d7)

A 100 by 100 meter right triangle with 45 degree angles (within the limits of my hand drawing) matches what we expect from geometry.  

Likewise a high latitude example being very incorrect:

![image](https://github.com/geomoose/gm3/assets/5263258/83474733-727b-4fa7-99f7-eefbe3136e1f)

Does OpenLayers do some underlying tricks for 3857 bearings?  If so that could be considered, otherwise, UTM (or some other local grid) is appropriate for bearings on the "local" scale (city, county, state; breaks down by continent).  For convenience, I'm ignoring the convergence angle since I think that starts to get to a level of complexity beyond most GeoMoose site configurations and uses).

**Comment by klassenjs** [comment]
It must not actually be doing the math in 4326 proper (spherical), but doing the math using 4326 coordinates but as a rectilinear coordinate system.  Then the aspect ratio gets more squished the further from the equator.

![image](https://github.com/geomoose/gm3/assets/165622/83191000-74ab-4a83-b755-c590d228927e)

![image](https://github.com/geomoose/gm3/assets/165622/58996762-8f22-41c7-bb58-94937026e654)


But, either way, in the demo area, Grid North (UTM15), True North, and Magnetic North are all effectively the same (just luck of where the magnetic pole is and that the demo area is about central in the UTM zone).

![image](https://github.com/geomoose/gm3/assets/165622/b113b3ba-abc9-401e-b796-c1b3012f2657)
https://mdd.sharedgeo.org/mdd-gen?date=2019.0&lat=44.55&lon=-93.15&zone=15&of=png&width=150&height=180&submit=Generate+MDD

So, I think there are two issues here:

1. Defining what we mean by North.  My guess is True North is what we should be using.  Using UTM grid north can be noticeably off from True North, is somewhat arbitrary, (and doesn't even make sense over the poles eg. EPSG:3413).  Magnetic north moves around all the time and requires updated model data so probably isn't something we want to deal with.
2. Applying rectilinear math on a spherical coordinate system

**Comment by elil** [comment]
Magnetic north- this is worse than spherical triangles, I agree, magnetic north isn't something we want to deal with.

Using UTM (or any other local grid) adopts grid north which typically matches true north near the central meridian (see also other types of projections).  This means it matches in that area and then is off a systematic amount in other areas towards the edges (like @klassenjs says a convergence angle of 2-3 degrees plus and minus at each edge of the grid is to be expected).  I think that this is fine and applying the convergence angle is up to the user if they want to (or they default to grid bearings).  I think that we should adopt grid north as our north, complete with the limitations that come with this choice.  This also appears to be our previous behavior.  

Yes, it is true that the existing math is not showing geodetic bearings (that perhaps would have worked correctly) but rather some (inappropriate) rectilinear math with spherical coordinates.  I don't think that we want to go full geodetic or wander into spherical triangles. Going full geodetic could be an option in the future (and increasingly so as proj advances).  I think that this should be a separate future development (if we want to pursue it).

**Comment by klassenjs** [comment]
If we go with grid north, and we are dynamically picking a grid other than the displayed map projection, I think we need to at least state which grid we are using.  (Although, this is really just another symptom of "everything is 3857" not being good enough.)

**Comment by elil** [comment]
Stating the grid could be useful.  That level of detail may be more appropriate in the documentation rather than the UI.  Hopefully configurable to include or not and subtle.  You won't hear me cheering for 3857.

**Comment by elil** [comment]
Another approach of leaving the convergence angle to the user would be to have a user input field on the measure line tool like 

Rotation: `-2.4`

and then we apply that to all the bearings results.  That lets the user either use default local grid north or determine the convergence angle and apply it.  This would add complexity to the tool (at least on the user side, it would leave a do nothing, accept zero -or some other configured default, and use the results path).  If going this route, configuring a default rotation would be really helpful since in many cases the admin can "determine the convergence angle" and the user might not be able to readily do that.

**Comment by theduckylittle** [comment]
Updated code piggy backs on the UTM code used for length calculation. We could bring in geographiclib but this latest change will fix the difference between 3.10/3.11 and also ensure the line math is all in a consistent projection.

**Comment by chughes-lincoln** [comment]
Fixed by https://github.com/geomoose/gm3/pull/837
