### ISSUE TITLE
Github labels for project or saved responses

### ISSUE THREAD

**Issue by elil** [geomoose/gm3#98]
I'm still not entirely sold on the "reporter closes issue" method we use.  I agree that it is a superior method since the person who reported and saw an issue is the one reviewing and closing.  I'd like our method to be more obvious to the reporter if we are using it.  (random example, #87)

We could add a label of "review" or "ready for review by reporter" or we could use saved responses where we just name the user and then put in a saved response.  A few proposed saved responses below.  

[@theduckylittle] [work has been completed on this issue and is ready for review visible in https://demo.geomoose.org/3.0/desktop/.  Please review and test, reporting results here..]

[@theduckylittle] [work has been completed on this issue and is ready for review.  This is not visible in https://demo.geomoose.org/3.0/desktop/ and requires an independent configuration for testing and review.  Please review and test, reporting results here.]

[@theduckylittle] [work has been completed on this issue and is ready for review.  This is not visible in https://demo.geomoose.org/3.0/desktop/ due to lack of access to specific hardware.  Please review and test, reporting results here.]

[@theduckylittle] [work has been completed on this issue and is ready for review.  This is not visible in https://demo.geomoose.org/3.0/desktop/ due to lack of access to url or configuration of reporter.  Please review and test, reporting results here.]

**Comment by klassenjs** [comment]
We had a 'review' label in geomoose/geomoose.  Specifically asking the user to review would clarify the intent and I'd think would be more likely to get results especially in the case where the user isn't a regular contributor.  We could put a time limit on it (e.g. if no review/comments in 2 weeks we will close the issue).

Setting the review label is nice since it can take it out of the TODO list (at least temporarily) so devs don't keep tripping over it.  Adding the review request (which unfortunately isn't a native GitHub feature) is good when we want a user to help test the fix.  I doesn't necessarily have to be both all the time.

**Comment by theduckylittle** [comment]
We can add the review label back, that's pretty easy.

**Comment by theduckylittle** [comment]
Hey, look at this! REVIEW ME.

**Comment by elil** [comment]
Nice!  The label will certainly be handy for people in the know.  

I agree with @klassenjs that specifically asking for action (and explaining) is more likely to get a response.

**Comment by theduckylittle** [comment]
Good enough to close this issue?  We back channel a lot which is  helpful...

**Comment by elil** [comment]
Sure, I'll close.  If people aren't responding to the label down the road, then I'll reopen for saved responses.
